FROM ckan/ckan-base:2.10.10-py3.10 AS ckan

USER root

# Install any extensions needed by your CKAN instance
# See Dockerfile.dev for more details and examples
### Harvester ###
#RUN pip3 install -e 'git+https://github.com/ckan/ckanext-harvest.git@master#egg=ckanext-harvest' && \
COPY patches/ckanext-harvest ${APP_DIR}/src/ckanext-harvest
RUN    pip3 install -e ${APP_DIR}/src/ckanext-harvest/
RUN    pip3 install -r ${APP_DIR}/src/ckanext-harvest/requirements.txt
# will also require gather_consumer and fetch_consumer processes running (please see https://github.com/ckan/ckanext-harvest)

### Scheming ###
#RUN  pip3 install -e 'git+https://github.com/ckan/ckanext-scheming.git@master#egg=ckanext-scheming'

### Pages ###
#RUN  pip3 install -e git+https://github.com/ckan/ckanext-pages.git#egg=ckanext-pages

RUN pip3 install pylons
RUN pip3 install routes

# Install ckanext-dcat HVD
#RUN  pip3 install -e git+https://github.com/ckan/ckanext-dcat.git@56-tmp#egg=ckanext-dcat && \
COPY patches/ckanext-dcat ${APP_DIR}/src/ckanext-dcat
RUN     pip3 install -e ${APP_DIR}/src/ckanext-dcat/
RUN     pip3 install -r ${APP_DIR}/src/ckanext-dcat/requirements.txt

# Install ckanext-dcatapit
COPY patches/ckanext-dcatapit ${APP_DIR}/src/ckanext-dcatapit
RUN     pip3 install -e ${APP_DIR}/src/ckanext-dcatapit/

# X-Loader
RUN pip3 install --no-cache-dir \
    git+https://github.com/ckan/ckanext-xloader.git@2.2.0#egg=ckanext-xloader \
    && pip3 install --no-cache-dir \
    -r https://raw.githubusercontent.com/ckan/ckanext-xloader/2.2.0/requirements.txt

# Install ckanext-multilang
RUN  pip3 install -e git+https://github.com/geosolutions-it/ckanext-multilang.git@master#egg=ckanext-multilang  && \
     pip3 install -e ${APP_DIR}/src/ckanext-multilang/

# DCATAPIT theme to group mapping file
COPY patches/theme_to_group.ini "${APP_DIR}/patches/theme_to_group.ini"
RUN chmod 666 "${APP_DIR}/patches/theme_to_group.ini"

# OPENAIRE ESTENSIONI
COPY patches/ckanext-dcat-ap-edp-mqa ${APP_DIR}/src/ckanext-dcat-ap-edp-mqa
RUN     pip3 install -e ${APP_DIR}/src/ckanext-dcat-ap-edp-mqa
RUN     pip3 install -r ${APP_DIR}/src/ckanext-dcat-ap-edp-mqa/requirements.txt
COPY patches/ckanext-oai-pmh-server ${APP_DIR}/src/ckanext-oai-pmh-server
RUN     pip3 install -e ${APP_DIR}/src/ckanext-oai-pmh-server
RUN     pip3 install -r ${APP_DIR}/src/ckanext-oai-pmh-server/requirements.txt

# CKAN group to DCATAPIT theme mapping file
COPY patches/topics.json "${APP_DIR}/patches/topics.json"
RUN chmod 666 "${APP_DIR}/patches/topics.json"

# DCATAPIT regions vocabulary file
COPY patches/regions.rdf "${APP_DIR}/patches/regions.rdf"
RUN chmod 666 "${APP_DIR}/patches/regions.rdf"

COPY patches/model_dictize.py ${APP_DIR}/src/ckan/ckan/lib/dictization/model_dictize.py
COPY patches/base.py ${APP_DIR}/src/ckan/ckan/lib/base.py

COPY patches/xmlrpc.py /usr/local/lib/python3.10/site-packages/pylons/controllers/xmlrpc.py
COPY patches/jsonrpc.py /usr/local/lib/python3.10/site-packages/pylons/controllers/jsonrpc.py
COPY patches/core.py /usr/local/lib/python3.10/site-packages/pylons/controllers/core.py
COPY patches/supervisord.conf /etc/supervisord.conf
COPY patches/sprite-resource-icons.png "${APP_DIR}/src/ckan/ckan/public/base/images"
COPY patches/ckan_logo_col.png "${APP_DIR}/src/ckan/ckan/public/base/images"
# patch per user not auth to show in harvesting
COPY patches/__init__.py ${APP_DIR}/src/ckan/ckan/logic/__init__.py
# patch per avere il rating dal portale europeo dei dati aperti. Decommentare se si vuole il punteggio
#COPY patches/read.html "${APP_DIR}/src/ckan/ckan/templates/package/read.html"
# fix origin con landingpage e non /edit/
COPY patches/language_selector.html ${APP_DIR}/src/ckan/ckan/templates/snippets/language_selector.html
COPY patches/util.py ${APP_DIR}/src/ckan/ckan/views/util.py

#FIX per XLOADER per il comando ckan xloader status. Consigliato:
COPY patches/command.py /usr/local/lib/python3.10/site-packages/ckanext/xloader/command.py

# Min length resource = 5
COPY patches/validators.py ${APP_DIR}/src/ckan/ckan/logic/validators.py

# Copy custom initialization scripts
COPY docker-entrypoint.d/* /docker-entrypoint.d/

COPY patches/groups ${APP_DIR}/patches/groups

# Apply any patches needed to CKAN core or any of the built extensions (not the
# runtime mounted ones)
COPY patches ${APP_DIR}/patches

RUN for d in $APP_DIR/patches/*; do \
        if [ -d $d ]; then \
            for f in `ls $d/*.patch | sort -g`; do \
                cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
            done ; \
        fi ; \
    done


# Script manuale per il setup iniziale dei gruppi tematici (vedi README)
COPY setup_groups.sh ${APP_DIR}/setup_groups.sh
RUN chmod +x ${APP_DIR}/setup_groups.sh

# Utilita' di base (un solo layer, non interattivo)
RUN apt-get update \
    && apt-get install -y --no-install-recommends nano curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install setuptools==80
RUN pip3 install --no-cache-dir -U certifi
